#%RAML 1.0 NameExample
value:
  -
    airline: Indigo
    flightCode: IND102
    fromAirportCode: HYD
    toAirportCode: BLR
    departureDate: 13-feb-2020
    emptySeats: 24
    totalSeats: 350
    price: 450
    planeType: Indigo 747
  -     
    airline: Indigo
    flightCode: IND103
    fromAirportCode: HYD
    toAirportCode: BLR
    departureDate: 13-feb-2020
    emptySeats: 33
    totalSeats: 400
    price: 450
    planeType: Indigo 757
  
    